### ISSUE TITLE
I wrote an article about ng2-resource-rest

### ISSUE THREAD

**Issue by Slaals** [troyanskiy/ng2-resource-rest#75]
Hi there, sorry it's not an issue, I just wanted to let you know that I wrote an article about your awesome library.

It is mostly inspired by your documentation.

Here is the article http://blog.slals.io/angular2-a-rest-client-interface

If you think it would be useful to anyone, feel free to reference it in the documentation, and of course I would be glad :)

Cheers, keep building!

**Comment by troyanskiy** [comment]
Hi! That is really awesome! Thank you!
I just have one remark on your example how to use service (also in my example). Probably you should add some remark about that call `let book: IBook = this._bookService.getBook({id: 42});`. It work asynchronous it means that you will have to wait until the data will be received and than change the title `book.title = 'Ainsi parlait Zarathoustra';`
So other beginner developers will understand that.

So it will be something like that
```typescript
let book: IBook = this._bookService.getBook({id: 42});
book.$observable
  .toPromise()
  .then(() => {
    book.title = 'Ainsi parlait Zarathoustra';
    return this._bookService.updateBook(book).$observable.toPromise();
  })
  .then(() => {
    return this._bootService.deleteBook(book).$observable.toPromise();
  });
```

**Comment by Slaals** [comment]
Ah, interesting! I made the RestClient but I only tried to do some GET requests.

Thanks, I'll update that and adds some details about this :)

**Comment by troyanskiy** [comment]
I've read your conclusion and the thing, which you don't like. So I've just released 1.8.0 version which allows you to add custom params to resource or method decorators. So now, can make requests without Auth where it's not required.

**Comment by Slaals** [comment]
That's one of a fast update! Really thank you, I'm happy to have that now!

**Comment by Slaals** [comment]
There is an issue with custom fields in ResourceActionBase, for instance 

```
@ResourceAction({
    method: RequestMethod.Post,
    path: '/refresh',
    auth: true
  })
  refresh: ResourceMethod<void, any>;
```

Make the following error

`Property 'auth' does not exist on type 'ResourceActionBase'`

I'm not used to TypeScript so I don't really know what is the behavior of `[propName: string]: any` in `ResourceParamsCommon`

**Comment by troyanskiy** [comment]
I believe you have that error in `getHeaders` method (I had).
Just change param time to any
```typescript
getHeaders(methodOptions: any): any {
    let headers = super.getHeaders();

    // Extending our headers with Authorization
    if (!methodOptions.noAuth) {
      headers = AuthServiceHelper.extendHeaders(headers);
    }

    return headers;
  }
```

**Comment by Slaals** [comment]
For `getHeaders` typing the param to `any` works. But there is still an issue from the resource handler, in your documentation you put something like 

```
@ResourceAction({
    method: RequestMethod.Post,
    path: '/login',
    // Custom param
    noAuth: true
  })
  login: ResourceMethod<{login: string, password: string}, any>;
```

Here, `noAuth` would trigger an error because it's an unknown property. I don't know how index signature behaves within a decorator, does it work with you?

**Comment by troyanskiy** [comment]
try:
`npm uninstall ng2-resource-rest`
`npm install ng2-resource-rest`

**Comment by Slaals** [comment]
I did check if everything was up to date (it is), I tried to uninstall / install but I still have this issue.

I will investigate, could you confirm that the issue is not because of the decorator? I'm not so sure about this, but it looks like the decorator `@ResourceAction` is the problem.

Again the error I get is `Property 'auth' does not exist on type 'ResourceActionBase'`

**Comment by troyanskiy** [comment]
Strange thing...
I don't have errors with Ionic2 nor [angular-seed](https://github.com/mgechev/angular-seed).
Can you publish your sources somewhere so I can check and test?

**Comment by Slaals** [comment]
Hum... Okay it's very strange, if you don't find where the issue is, I'll try to find by myself since the problem is from my side.

https://github.com/woobleio/wooble/blob/dev/src/app/shared/session.service.ts#L29

So, for instance when I put a custom field here 

```
@ResourceAction({
    method: RequestMethod.Post,
    path: '/refresh',
    auth: true // <- Property 'auth' does not exist on type 'ResourceActionBase'
  })
  refresh: ResourceMethod<void, any>;
```

I got an error. TS version is `2.1.0`

**Comment by troyanskiy** [comment]
Try to play with your tsconfig.json
Check how it's done in `angular-seed` [tsconfig.json](https://github.com/mgechev/angular-seed/blob/master/src/client/tsconfig.json)

**Comment by Slaals** [comment]
Okay I'll look at it, thank. I won't take your time anymore, the issue if from my side for sure and it's not urgent. I'll comeback to update about the problem and the solution.

Have a good day, and again thanks for your real quick update :)

**Comment by troyanskiy** [comment]
Great. It will be nice to know the solution of the problem.
Have a great day and thanks again for great article.

**Comment by Slaals** [comment]
Time did solve the issue :o

I don't really know what happened, I didn't do anything to fix it. My guess is that Atom and tslinter were to blame, it told me there was an error even though there wasn't!

Everything works fine now :)
